from datetime import timedelta

from test import Test


QUICK_TESTS = [
    Test(name="copyin",     timeout=timedelta(seconds=20)),
    Test(name="copyout",    timeout=timedelta(milliseconds=200)),
    Test(name="copyinstr1", timeout=timedelta(milliseconds=200)),
    Test(name="copyinstr2", timeout=timedelta(milliseconds=200)),
    Test(name="copyinstr3", timeout=timedelta(milliseconds=200)),
    Test(name="rwsbrk",     timeout=timedelta(seconds=1)),
    Test(name="truncate1",  timeout=timedelta(seconds=2)),
    Test(name="truncate2",  timeout=timedelta(seconds=2)),
    Test(name="truncate3",  timeout=timedelta(seconds=40)),
    Test(name="openiput",   timeout=timedelta(seconds=1)),
    Test(name="exitiput",   timeout=timedelta(seconds=1)),
    Test(name="iput",       timeout=timedelta(seconds=1)),
    Test(name="opentest",   timeout=timedelta(seconds=1)),
    Test(name="writetest",  timeout=timedelta(seconds=8)),
    Test(name="writebig",   timeout=timedelta(seconds=30)),
    Test(name="createtest", timeout=timedelta(seconds=30)),
    Test(name="dirtest",    timeout=timedelta(seconds=1)),
    Test(name="exectest",   timeout=timedelta(seconds=2)),
    Test(name="pipe1",      timeout=timedelta(milliseconds=500)),
    Test(name="killstatus", timeout=timedelta(seconds=12)),
    Test(
        name="preempt",
        suffix_size=len("kill... wait... "),
        timeout=timedelta(milliseconds=500),
    ),
    Test(name="exitwait",       timeout=timedelta(seconds=1)),
    Test(name="reparent",       timeout=timedelta(seconds=3)),
    Test(name="twochildren",    timeout=timedelta(seconds=10)),
    Test(name="forkfork",       timeout=timedelta(seconds=3)),
    Test(name="forkforkfork",   timeout=timedelta(seconds=8)),
    Test(name="reparent2",      timeout=timedelta(seconds=15)),
    Test(name="mem",            timeout=timedelta(seconds=5)),
    Test(name="sharedfd",       timeout=timedelta(seconds=20)),
    Test(name="fourfiles",      timeout=timedelta(seconds=5)),
    Test(name="createdelete",   timeout=timedelta(seconds=45)),
    Test(name="unlinkread",     timeout=timedelta(seconds=2)),
    Test(name="linktest",       timeout=timedelta(seconds=2)),
    Test(name="concreate",      timeout=timedelta(seconds=70)),
    Test(name="linkunlink",     timeout=timedelta(seconds=12)),
    Test(name="subdir",         timeout=timedelta(seconds=5)),
    Test(name="bigwrite",       timeout=timedelta(seconds=30)),
    Test(name="bigfile",        timeout=timedelta(seconds=2)),
    Test(name="fourteen",       timeout=timedelta(seconds=2)),
    Test(name="rmdot",          timeout=timedelta(seconds=2)),
    Test(name="dirfile",        timeout=timedelta(seconds=2)),
    Test(name="iref",           timeout=timedelta(seconds=12)),
    Test(name="forktest",       timeout=timedelta(seconds=1)),
    Test(name="sbrkbasic",      timeout=timedelta(seconds=3)),
    Test(name="sbrkmuch",       timeout=timedelta(seconds=2)),
    Test(
        name="kernmem",
        timeout = timedelta(milliseconds=500),
        suffix_size=len("usertrap(): unexpected scause 0xd pid=6452"),
        extra_lines=79,
    ),
    Test(
        name="MAXVAplus", 
        timeout=timedelta(seconds=30),
        suffix_size=len("usertrap(): unexpected scause 0xf pid=6515"),
        extra_lines=51,
    ),
    Test(
        name="sbrkfail",
        timeout=timedelta(seconds=1),
        suffix_size=len("usertrap(): unexpected scause 0xd pid=6553"),
        extra_lines=1
    ),
    Test(name="sbrkarg", timeout=timedelta(seconds=10)),
    Test(name="validatetest", timeout=timedelta(seconds=10)),
    Test(name="bsstest", timeout=timedelta(seconds=10)),
    Test(name="bigargtest", timeout=timedelta(seconds=10)),
    Test(name="argptest", timeout=timedelta(seconds=10)),
    Test(
        name="stacktest",
        timeout=timedelta(seconds=10),
        suffix_size=len("usertrap(): unexpected scause 0xd pid=6561"),
        extra_lines=1,
    ),
    Test(
        name="nowrite",
        timeout=timedelta(seconds=10),
        suffix_size=len("usertrap(): unexpected scause 0xf pid=6563"),
        extra_lines=11,
    ),
    Test(name="pgbug",timeout=timedelta(seconds=10)),
    Test(
        name="sbrkbugs",
        timeout=timedelta(seconds=10),
        suffix_size=len("usertrap(): unexpected scause 0xc pid=6571"),
        extra_lines=3,
    ),
    Test(name="sbrklast",timeout=timedelta(seconds=10)),
    Test(name="sbrk8000",timeout=timedelta(seconds=10)),
    Test(name="badarg",timeout=timedelta(seconds=10)),
]
